### ISSUE TITLE
Prepare Workshop Presentation for Dataverse Community Meeting 

### ISSUE THREAD

**Issue by ekraffmiller** [IQSS/dataverse-frontend#300]
We will be presenting a 1 hour workshop at the DCM. It will be an overview of the current status of the SPA project, and a guide for developers who want to start using the new Design System and js-dataverse (Javascript client library)

This task is be broken out into smaller issues. There may be more issues added presentation content is finalized.
- [ ] Create presentation slides https://github.com/IQSS/dataverse-frontend/issues/302
- [ ] Create Demo Repository: https://github.com/IQSS/dataverse-frontend/issues/301
- [ ] New Documentation for js-dataverse: https://github.com/IQSS/dataverse-client-javascript/pull/118
- [ ] New Front End Guides: https://github.com/IQSS/dataverse-frontend/issues/26

**Comment by ekraffmiller** [comment]
completed
